//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQ2CollQuests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EQ2CollQuests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en-us&quot;&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;EQ2 Collection Quests Help - Character Page&lt;/title&gt;
        ///&lt;meta charset=&quot;UTF-8&quot;&gt;
        ///&lt;meta name=&quot;Author&quot; content=&quot;Erik Jepsen&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;h1&gt;The Character Page&lt;/h1&gt;
        ///&lt;p&gt;The Character Page is broken up into three main parts: The Character List, The Character&apos;s Quest List, The Character&apos;s Quest&apos;s Items.&lt;/p&gt;
        ///&lt;h2&gt;The Character List&lt;/h2&gt;
        ///&lt;p&gt;This area lists your characters in alphabetical order. The buttons at the bottom of the list allow you to add addition [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CharacterPage {
            get {
                return ResourceManager.GetString("CharacterPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en-us&quot;&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;EQ2 Collection Quests Help&lt;/title&gt;
        ///&lt;meta charset=&quot;UTF-8&quot;&gt;
        ///&lt;meta name=&quot;Author&quot; content=&quot;Erik Jepsen&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;p&gt;This application and its accompanying help files were written by &lt;a href=&quot;mailto:erik@jepster.com&quot;&gt;Erik Jepsen&lt;/a&gt;, &amp;copy;2020. All rights reserved.&lt;/p&gt;
        ///&lt;ul&gt;
        ///&lt;li&gt;&lt;a href=&quot;CharacterPage.html&quot;&gt;Characters Page&lt;/a&gt;&lt;/li&gt;
        ///&lt;li&gt;&lt;a href=&quot;QuestsPage.html&quot;&gt;Quests Page&lt;/a&gt;&lt;/li&gt;
        ///&lt;li&gt;&lt;a href=&quot;ItemsPage.html&quot;&gt;Items Page&lt;/a&gt;&lt;/li&gt;
        ///&lt;li&gt;&lt;a href=&quot;S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EQ2CollQuests {
            get {
                return ResourceManager.GetString("EQ2CollQuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\deff3\adeflang1025
        ///{\fonttbl{\f0\froman\fprq2\fcharset0 Times New Roman;}{\f1\froman\fprq2\fcharset2 Symbol;}{\f2\fswiss\fprq2\fcharset0 Arial;}{\f3\froman\fprq2\fcharset0 Liberation Serif{\*\falt Times New Roman};}{\f4\fswiss\fprq2\fcharset0 Liberation Sans{\*\falt Arial};}{\f5\froman\fprq2\fcharset128 Georgia;}{\f6\fnil\fprq2\fcharset0 Microsoft YaHei;}{\f7\fswiss\fprq0\fcharset128 Arial;}{\f8\fnil\fprq2\fcharset0 Arial;}}
        ///{\colortbl;\red0\green0\blue0;\red0\green0\blue255;\red0\green255\blu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExpertMultExpl {
            get {
                return ResourceManager.GetString("ExpertMultExpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en-US&quot;&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;Items Page&lt;/title&gt;
        ///&lt;meta charset=&quot;UTF-8&quot;&gt;
        ///&lt;meta name=&quot;Author&quot; content=&quot;Erik Jepsen &lt;erik@jepster.com&gt;&quot;&gt;
        ///&lt;meta name=&quot;Created&quot; content=&quot;2020-12-14T10:08Z-8&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;h1&gt;Items Page&lt;/h1&gt;
        ///&lt;p&gt;The items page is split between two general areas, the list of items and the information available for a selected item.&lt;/p&gt;
        ///&lt;h2&gt;Item List&lt;/h2&gt;
        ///&lt;p&gt;This list contains the items currently downloaded to your machine. In testing, this list exceeded 5,000 items. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ItemsPage {
            get {
                return ResourceManager.GetString("ItemsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en-US&quot;&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;Quests Page&lt;/title&gt;
        ///&lt;meta charset=&quot;UTF-8&quot;&gt;
        ///&lt;meta name=&quot;Author&quot; content=&quot;Erik Jepsen &lt;erik@jepster.com&gt;&quot;&gt;
        ///&lt;meta name=&quot;Created&quot; content=&quot;2020-12-14T09:28Z-8&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;h1&gt;Quests&lt;/h1&gt;
        ///&lt;p&gt;The quests page is divied up into three sections. On the left-hand column is a list of all the quests currently downloaded to your machine. The right-hand
        ///side is split between the information pane at the top and a tree of items underneath.&lt;/p&gt;
        ///&lt;h2&gt;Quest List [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QuestsPage {
            get {
                return ResourceManager.GetString("QuestsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en-US&quot;&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;Settings Page&lt;/title&gt;
        ///&lt;meta charset=&quot;UTF-8&quot;&gt;
        ///&lt;meta name=&quot;Author&quot; content=&quot;Erik Jepsen &lt;erik@jepster.com&gt;&quot;&gt;
        ///&lt;meta name=&quot;Created&quot; content=&quot;2020-12-14T10:39Z-8&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;h1&gt;Settings Page&lt;/h1&gt;
        ///&lt;h2&gt;The Settings&lt;/h2&gt;
        ///&lt;dl&gt;&lt;dt&gt;Go Online?&lt;/dt&gt;&lt;dd&gt;This (will eventually) control whether new items may be downloaded. Currently it is strictly decorative. Eventually, it will be useful
        ///if you are on a capped or otherwise limited connection. &lt;b&gt;Not curren [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SettingsPage {
            get {
                return ResourceManager.GetString("SettingsPage", resourceCulture);
            }
        }
    }
}
